### ISSUE TITLE
License report exclusion enhancements

### ISSUE THREAD

**Issue by stevendick** [hierynomus/license-gradle-plugin#111]
The current exclusion mechanism works on matching the full group:module:version string.

I couldn't get this to work for excluding source JARs for our own code in the build, so modified the exclusion matching logic to use String::startsWith instead. This reduced the amount of config I needed.

I would like to see either of the following options instead:
- regex matching
- support the same matching logic as when specifying dependency exclusions (based on group and module name)

**Comment by hierynomus** [comment]
I think I'll have a go at implementing the second option, this makes it more in line I think.

**Comment by damianoneill** [comment]
+1

**Comment by Jaykob** [comment]
+1

**Comment by hanleyt** [comment]
+1
