### ISSUE TITLE
How to generate JSON output and change output location?

### ISSUE THREAD

**Issue by sealskej** [hierynomus/license-gradle-plugin#116]
With default configuration I can export licenses to `HTML` and `XML`. How can I configure export to `JSON`?

Can I change output location, different from `build/reports`?

**Comment by hierynomus** [comment]
JSON was added some time ago.

You can configure the output location by changing the following property in your `build.gradle`

    downloadLicenses {
      report {
        json {
          destination = "<directory>"
        }
      }
    }

**Comment by hierynomus** [comment]
I think this is answered :)
