### ISSUE TITLE
Task fails when default `header` file is not found, even when a `headerURI` is set

### ISSUE THREAD

**Issue by ewortzman** [hierynomus/license-gradle-plugin#122]
I have my project set up to download a remote file containing the license.  I do not have a `LICENSE` file in the root of my project.  When this configuration exists, the plugin should ignore the default `header` setting and download the `headerURI` setting, unless the `headerURI` file cannot be found.

Instead, I get a failure that says the `header` file does not exist.

**Comment by hierynomus** [comment]
Hi @ewortzman,

What is the exception or message you're getting? Can you run with `-s` to get the stacktrace?

Thanks!

**Comment by ewortzman** [comment]
Nevermind I discovered the issue.

The problem was I configured this plugin as part of another plugin.  In other projects, if I apply my build plugin (which sets `header` to null) before applying this plugin, the nullified `header` is overwritten, so the build fails when it can't find the file.
