### ISSUE TITLE
Disable including license task in default check task

### ISSUE THREAD

**Issue by ewortzman** [hierynomus/license-gradle-plugin#124]
I'd like to prevent this from running every time `check` is run.  I want to manually have to call the license task.

Is this possible?

**Comment by hierynomus** [comment]
I think you can do `project.tasks.check.dependsOn -= <task to remove>`

**Comment by hierynomus** [comment]
In the upcoming 0.14.0 version I've split up the plugin into `com.github.hierynomus.license-base` and `com.github.hierynomus.license`. The `license-base` plugin will only add tasks for all the sourceSets, but does not actually hook them up into the lifecycle of the build, allowing you to finetune that. The `license` plugin is 'opinionated' and adds all of the `LicenseCheck` tasks to the `check` lifecycle task.
