### ISSUE TITLE
Honor Gradle's buildDir property

### ISSUE THREAD

**Issue by robertwenner** [hierynomus/license-gradle-plugin#127]
I have this build script:

```
plugins {
    id 'java'
    id 'com.github.hierynomus.license' version '0.13.1'
}
buildDir = 'generated'
```

When I run `gradle java`,  I get the .class files under `generated/` as expected.

When I run `gradle downLic`, it creates a folder named `build/` and puts its reports in that.

How can I change that? I think it would be best to honor the global `buildDir` (like other plugins do), but I can live with a configuration option in the license-gradle-plugin as well.

**Comment by hierynomus** [comment]
Good find. I'll fix that :)

**Comment by robertwenner** [comment]
Wow, you're fast! Awesome, thanks!
