### ISSUE TITLE
Android Lint warning: "Dangling Javadoc comment"

### ISSUE THREAD

**Issue by stkent** [hierynomus/license-gradle-plugin#129]
<img width="808" alt="screen shot 2017-03-06 at 9 57 10 pm" src="https://cloud.githubusercontent.com/assets/6463980/23639863/f05535dc-02b7-11e7-8e32-6a7a7fa6a15e.png">

Should this be formatted as a multi-line comment, rather than a Javadoc? Is that a configuration option that I missed someplace? 😳 

Thanks!

**Comment by hierynomus** [comment]
The configuration option is present, and documented, but might be easy to miss.

```
license {
  mapping {
    java='SLASHSTAR_STYLE'
  }
}
```

**Comment by stkent** [comment]
Ah, great, thanks, will check that out :)

**Comment by hierynomus** [comment]
Let me know if this solves it for you :)

**Comment by stkent** [comment]
Yep, this was exactly what I needed :)
