### ISSUE TITLE
downloadLicenses fails with Gradle 3.3 and Android Gradle Plugin 2.3.0

### ISSUE THREAD

**Issue by dmapr** [hierynomus/license-gradle-plugin#133]
The sample failing project is located here: https://github.com/dmapr/LicenseCollector. Note that changing the dependencyOptions inside downloadLicenses block from **compile** to **runtime** causes an empty table to be generated.

**Comment by hierynomus** [comment]
This seems to be the same issue as #134 which is now solved.
