### ISSUE TITLE
v0.14.0 not found

### ISSUE THREAD

**Issue by andhie** [hierynomus/license-gradle-plugin#136]
In the README docs, it states to use v0.14.0 of the plugin. 
however the latest version available on Gradle Plugin site (https://plugins.gradle.org/plugin/com.github.hierynomus.license) is 0.13.1 

```
Gradle sync failed: Plugin [id: 'com.github.hierynomus.license', version: '0.14.0'] was not found in any of the following sources:
	- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
	- Gradle Central Plugin Repository (plugin 'com.github.hierynomus.license' has no version '0.14.0' - see https://plugins.gradle.org/plugin/com.github.hierynomus.license for available versions)
	Consult IDE log for more details (Help | Show Log)
```

**Comment by hierynomus** [comment]
Hi @andhie,

Correct, I was preparing to release that version last week, but hadn't come around to finishing it.

The latest version is indeed 0.13.1. I will release 0.14.0 momentarily.

**Comment by hierynomus** [comment]
Released: https://plugins.gradle.org/plugin/com.github.hierynomus.license
