### ISSUE TITLE
Support for Gradle 4.0 for Android

### ISSUE THREAD

**Issue by arocha55** [hierynomus/license-gradle-plugin#137]
Hello,

When running :downloadLicenses task using Gradle 4.0 and Android Plugin 3.0.0-rc2 I am no longer able to get a full report of my dependencies and their license information. The task completes successfully, however when inspecting the reports (e.g. dependency-license.html) I noticed that it was only able to detect the Android Support Libraries, and furthermore it wasn't able to detect License name ("No license found") and License text URL shows up as blank.

I'm using Android Studio 3.0 preview from Canary release. Prior to upgrading to Gradle 4.0, the downloadLicense task was working accordingly with Gradle 3.0, so my guess is something broke with latest version of Gradle.

Thanks,
Alex

**Comment by jungc** [comment]
```
Execution failed for task 'downloadLicenses'.
> Resolving configuration 'implementation' directly is not allowed
```

This is also related to gradle backward compat issue

**Comment by kim1059** [comment]
any updates on this one? I think this is huge issue

**Comment by nkeywal** [comment]
It would be great to have this fixed. For a new project starting with the new gradle syntax, using android or not, the error (or more precisely, the absence of any error) is quite misleading. Moreover, if, by accident, you use the new syntax for a single dependency, this dependency will just be ignored: it's quite easy to miss it.
