### ISSUE TITLE
Plugin ID com.github.hierynomus.license-base not published to Gradle Plugin Portal

### ISSUE THREAD

**Issue by radarsh** [hierynomus/license-gradle-plugin#144]
When we try to use the `license-base` plugin by using the following snippet, the build fails. 

```
plugins {
  id "com.github.hierynomus.license-base" version"0.14.0"
}
```

Turns out this is because the `license-base` [plugin hasn't been published to Gradle Plugin Portal](https://plugins.gradle.org/plugin/com.github.hierynomus.license-base).

**Comment by hierynomus** [comment]
Thanks, I think that's due to a misconfiguration of the build file :).

You can try to use the 'old-style' plugin format (i.e. `buildSource { ... }` and `apply plugin:`). That should work, as the code is there.

**Comment by radarsh** [comment]
We don't mind waiting for the next proper release into Gradle plugin portal. We're specifically interested in the `com.github.hierynomus.license-base` plugin as we found out that with the `com.github.hierynomus.licence` version, it was trying to invoke other tasks from other source sets when we didn't intend to.

**Comment by radarsh** [comment]
Hi @hierynomus did you manage to publish a proper release of the plugins? We would like to use this in our project but unfortunately can't do so until the correct plugin IDs are published to Gradle Plugin Portal.

**Comment by radarsh** [comment]
We found an alternative, https://github.com/Minecrell/licenser which seems to fit our bill nicely.
