### ISSUE TITLE
Version 0.15.0 is not deployed to https://plugins.gradle.org/m2/

### ISSUE THREAD

**Issue by dmitry-weirdo** [hierynomus/license-gradle-plugin#175]
https://plugins.gradle.org/m2/gradle/plugin/nl/javadude/gradle/plugins/license-gradle-plugin/
does not contain version 0.15.0.

Because of this, the build in "old gradle" form fails with:

> FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'myProject'.
> Could not resolve all files for configuration ':classpath'.
   > Could not find gradle.plugin.nl.javadude.gradle.plugins:license-gradle-plugin:0.15.0.
     Searched in the following locations:
         https://jcenter.bintray.com/gradle/plugin/nl/javadude/gradle/plugins/license-gradle-plugin/0.15.0/license-gradle-plugin-0.15.0.pom
         https://jcenter.bintray.com/gradle/plugin/nl/javadude/gradle/plugins/license-gradle-plugin/0.15.0/license-gradle-plugin-0.15.0.jar
         https://repo.maven.apache.org/maven2/gradle/plugin/nl/javadude/gradle/plugins/license-gradle-plugin/0.15.0/license-gradle-plugin-0.15.0.pom
         https://repo.maven.apache.org/maven2/gradle/plugin/nl/javadude/gradle/plugins/license-gradle-plugin/0.15.0/license-gradle-plugin-0.15.0.jar
         https://plugins.gradle.org/m2/gradle/plugin/nl/javadude/gradle/plugins/license-gradle-plugin/0.15.0/license-gradle-plugin-0.15.0.pom
         https://plugins.gradle.org/m2/gradle/plugin/nl/javadude/gradle/plugins/license-gradle-plugin/0.15.0/license-gradle-plugin-0.15.0.jar
     Required by:
         project :

**Comment by sid2986** [comment]
Using ` nl.javadude.gradle.plugins:license-gradle-plugin:0.10.0` in dependencies worked for me as 0.15.0 was not available as mentioned by the OP.

**Comment by sid2986** [comment]
Am not sure if this is deliberate as I found the latest version in the below : -
https://plugins.gradle.org/m2/com/github/hierynomus/license/com.github.hierynomus.license.gradle.plugin/0.15.0/

**Comment by ketan** [comment]
Bump. I'm facing the same issue. Is this published somewhere else?

**Comment by ketan** [comment]
I just noticed that the maven co-ordinates for the plugin have changed:

```gradle
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }

  dependencies {
    classpath 'gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin:0.15.0'
  }
}

```

**Comment by arulrajnet** [comment]
[Readme](https://github.com/hierynomus/license-gradle-plugin/blob/master/README.adoc#gradle-1x20-latest-license-gradle-plugin) has to be updated.
