### ISSUE TITLE
Gradle 6 compatibility - missing task annotations

### ISSUE THREAD

**Issue by rpalcolea** [hierynomus/license-gradle-plugin#179]
Gradle 6.x is more aggressive when validation task configurations:

```

 - Property 'check' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'dryRun' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'encoding' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'headerDefinitions' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'inheritedMappings' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'inheritedProperties' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'internalMappings' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'skipExistingHeaders' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'strictCheck' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'URI' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'useDefaultMappings' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
 - Property 'validHeaders' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.

```

It would be great if the task could be properly annotated

**Comment by hierynomus** [comment]
Thanks for the issue. I'll have a look.

**Comment by rpalcolea** [comment]
Hi @hierynomus , 

Any chance you can take a look at this? 

Have a good day!

**Comment by rpalcolea** [comment]
I see that this was fixed in https://github.com/hierynomus/license-gradle-plugin/commit/25b456513aed45c725b657655f2ba0527b5341d2

Are there plans for a release soon @hierynomus ?

**Comment by tbroyer** [comment]
Any chance for a 0.16.0 anytime soon? Thanks in advance.

**Comment by chali** [comment]
hi @hierynomus little poke :-) can we help somehow?

**Comment by rpalcolea** [comment]
Hi @hierynomus, little poke. Any chance you could release 0.16.0 with the fix for this? thanks in advance!

**Comment by TheDGOfficial** [comment]
Any updates on the 0.16.0 release? I'm waiting for this too.

**Comment by chali** [comment]
Hi @hierynomus can I help anyhow to get this change released? In Gradle 7.x those warnings change to hard failures and we start to be blocked. Thanks for your help!

**Comment by msgilligan** [comment]
... and since Gradle 6.x doesn't support the new JDK 16, the only way to support JDK 16 in a Gradle build is to disable the license plugin and upgrade to Gradle 7.

**Comment by tbroyer** [comment]
Well, you can actually use Gradle 6 with JDK 16: https://melix.github.io/blog/2021/03/gradle-java16.html

**Comment by msgilligan** [comment]
Well, that's a bit of a hack and only runs the "toolchain" with JDK 16. Among other issues, running the toolchain at JDK 16 with the Gradle daemon still at JDK 15 can cause some plugins to fail with "unrecognized major.minor version".

**Comment by rpalcolea** [comment]
Depends on how you see it. For me decoupling the JDK that it is used for my application from the one that Gradle uses is a good practice at the end, it wasn't possible before or at least not as easy as with Toolchain. So I'd say that definitely not a hack

**Comment by msgilligan** [comment]
It's a nice Gradle feature - definitely not a hack -- but there are (at least) 3 issues with it:

1. It creates additional installation and configuration requirements for anyone that wants to build from source
2. It requires installing two JDKs on your CI system
3. Plugins still run in the Gradle VM and if they can break when the toolchain VM is a different version (for example: https://github.com/beryx/badass-jlink-plugin/issues/176)

I have a project that I want to upgrade to use JDK16 and I'm blocked by Gradle, the (soon to be fixed 🤞) Gradle JLink Plugin, and this plugin. I think I'm going to have to switch to a different license plugin.

BTW, Gradle 7.0-RC1 is now available: https://gradle.org/release-candidate/
