### ISSUE TITLE
Is this repository no longer maintained?

### ISSUE THREAD

**Issue by king-tyler** [hierynomus/license-gradle-plugin#188]
There hasn't been any activity in this repository for 10 months and v0.16.0 hasn't been released that fixes the numerous Gradle 6 deprecation warnings (see https://github.com/hierynomus/license-gradle-plugin/issues/179#issuecomment-573943869).

Is there an actively maintained fork or alternative Gradle plugin that anybody knows of?

**Comment by jens-meiss** [comment]
i tried this plugin to generate the license report, looks good so far:

* https://github.com/jk1/Gradle-License-Report

**Comment by hlascelles** [comment]
That one looks good, but we need this one in particular for use with license_finder: https://github.com/pivotal/LicenseFinder#gradle-projects

**Comment by hierynomus** [comment]
Yes, picking this back up. Sorry to have been away too long.
