### ISSUE TITLE
Gradle 7.0: missing an input or output annotation

### ISSUE THREAD

**Issue by akarnokd** [hierynomus/license-gradle-plugin#191]
Hi. I upgraded to Gradle 7.0 and it now gives the following errors:

  - Type 'LicenseCheck' property 'URI' is missing an input or output annotation.
  - Type 'LicenseCheck' property 'check' is missing an input or output annotation.
  - Type 'LicenseCheck' property 'dryRun' is missing an input or output annotation.
  - Type 'LicenseCheck' property 'encoding' is missing an input or output annotation.
  - Type 'LicenseCheck' property 'headerDefinitions' is missing an input or output annotation.
    
>    Reason: A property without annotation isn't considered during up-to-date checking.
>    
>    Possible solutions:
>      1. Add an input or output annotation.
>      2. Mark it as @Internal.
>    
>    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation for more details about this problem.

Please advise.

**Comment by hlascelles** [comment]
Related: https://github.com/hierynomus/license-gradle-plugin/issues/188
Related: https://github.com/hierynomus/license-gradle-plugin/issues/179

If @hierynomus [could release 0.16.0](https://github.com/hierynomus/license-gradle-plugin/issues/179#issuecomment-573943869) please that would be much appreciated!

**Comment by rising3** [comment]
@hierynomus 

Hi, I  hope for new release :smile:

**Comment by hierynomus** [comment]
#192 Is being worked on to create a new release.

**Comment by hierynomus** [comment]
Just merged #192. Noticed that the integration tests were also outdated. Which caught another few missing task annotations.

**Comment by hierynomus** [comment]
And 0.16.1 is released! Sorry for the long wait
