### ISSUE TITLE
Add support for Antlr4

### ISSUE THREAD

**Issue by JonathanxD** [hierynomus/license-gradle-plugin#200]
Antlr4 uses the `*.g4` extension in their lexer and parser grammar files, it would be nice to see this plugin supporting them. Antlr4 uses the same `JAVADOC_STYLE` as Java does.

## Current Workaround
The current workaround is to add a mapping for `g4`:
```kotlin
tasks.withType<nl.javadude.gradle.plugins.license.License> {
    header = rootProject.file("LICENSE")
    strictCheck = true
    mapping("g4", "JAVADOC_STYLE")
}
```

And it works just fine, but only to generate license headers, as I've found while writing this issue... Since Antlr4 generates source files from grammar declarations, everytime I run `build` task, the `licenseMain` task fails complaining about license violation. There are currently only two (that I know that works) solutions:

Adding dependency on `licenseFormat` for the `generateGrammarSource` task:
```kotlin
tasks.generateGrammarSource {
    finalizedBy("licenseFormat")
}
```

Or excluding `generated-src` using predicates:

```kotlin
tasks.withType<nl.javadude.gradle.plugins.license.License> {
    exclude { !it.path.startsWith("$buildDir/generated-src/antlr") }
}
```

Tried `exclude("$buildDir/generated-src/antlr/**)` and it didn't worked (I even tried other variants, like `exclude("**/generated-src/**")` but didn't worked as well).

I don't know if this second issue could be addressed or would be a good fit to be addressed by this plugin, but at least supporting `*.g4` extensions would be very nice.

**Comment by hierynomus** [comment]
I've added the g4 extension mapping to the default mappings.

For the exclude variants that don't work, I would recommend to create a separate issue, as those should work.

I think the solution you've found for the generated-src which adds the `licenseFormat` as a finalizer task is the nicest one.
