### ISSUE TITLE
Empty report for Gradle 7.3 and Java 17

### ISSUE THREAD

**Issue by amikmr1** [hierynomus/license-gradle-plugin#207]
Hello and thanks for such a nice tool!

For some reason though, the reports are empty when using Gradle 7.3 and JDK 17

Gradle Distribution: Gradle wrapper from target build
Gradle Version: 7.3
Java Home: C:\tools\JDK\17
Gradle Tasks: downloadLicenses

While am trying to figure out if something is wrong from my side, just thought of mentioning this fact to you.

Thanks again.

=======================================================================

Edit: The problem is with version 0.16.1. When tried with version 0.15.0, i get the below issues:

> Task :XXXX:downloadLicenses FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':XXXX:downloadLicenses' (type 'DownloadLicenses').
  - In plugin 'com.github.hierynomus.license-base' type 'nl.javadude.gradle.plugins.license.DownloadLicenses' property 'html' has redundant getters: 'getHtml()' and 'isHtml()'.
    
    Reason: Boolean property 'html' has both an `is` and a `get` getter.
    
    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.
    
    Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#redundant_getters for more details about this problem.
  - In plugin 'com.github.hierynomus.license-base' type 'nl.javadude.gradle.plugins.license.DownloadLicenses' property 'ignoreFatalParseErrors' has redundant getters: 'getIgnoreFatalParseErrors()' and 'isIgnoreFatalParseErrors()'.
    
    Reason: Boolean property 'ignoreFatalParseErrors' has both an `is` and a `get` getter.
    
    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.
    
    Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#redundant_getters for more details about this problem.
  - In plugin 'com.github.hierynomus.license-base' type 'nl.javadude.gradle.plugins.license.DownloadLicenses' property 'includeProjectDependencies' has redundant getters: 'getIncludeProjectDependencies()' and 'isIncludeProjectDependencies()'.
    
    Reason: Boolean property 'includeProjectDependencies' has both an `is` and a `get` getter.
    
    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.
    
    Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#redundant_getters for more details about this problem.
  - In plugin 'com.github.hierynomus.license-base' type 'nl.javadude.gradle.plugins.license.DownloadLicenses' property 'json' has redundant getters: 'getJson()' and 'isJson()'.
    
    Reason: Boolean property 'json' has both an `is` and a `get` getter.
    
    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.
    
    Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#redundant_getters for more details about this problem.
  - In plugin 'com.github.hierynomus.license-base' type 'nl.javadude.gradle.plugins.license.DownloadLicenses' property 'reportByDependency' has redundant getters: 'getReportByDependency()' and 'isReportByDependency()'.
    
    Reason: Boolean property 'reportByDependency' has both an `is` and a `get` getter.
    
    Possible solutions:
      1. Remove one of the getters.
      2. Annotate one of the getters with @Internal.
    
    Please refer to https://docs.gradle.org/7.3/userguide/validation_problems.html#redundant_getters for more details about this problem.

**Comment by robsonke** [comment]
See https://stackoverflow.com/questions/67393005/gradle-get-list-of-dependencies-and-licenses for a solution/workaround.

**Comment by amikmr1** [comment]
[> See https://stackoverflow.com/questions/67393005/gradle-get-list-of-dependencies-and-licenses for a solution/workaround.](https://github.com/hierynomus/license-gradle-plugin/issues/207#issuecomment-1209313000)

Working now. Thanks!
