### ISSUE TITLE
Latest release incompatible with JDK6

### ISSUE THREAD

**Issue by aalmiray** [hierynomus/license-gradle-plugin#35]
Got the following error when running a build on Travis using jdk6

```
Execution failed for task ':licenseMain'.
> nl/javadude/gradle/plugins/license/maven/LicenseCheckMojo : Unsupported major.minor version 51.0
```

**Comment by xumingming** [comment]
using `0.13.1` still got this:

```java
FAILURE: Build failed with an exception.

* What went wrong:
java.lang.UnsupportedClassVersionError: nl/javadude/gradle/plugins/license/LicensePlugin : Unsupported major.minor version 51.0
> nl/javadude/gradle/plugins/license/LicensePlugin : Unsupported major.minor version 51.0
```

**Comment by hierynomus** [comment]
Correct, 0.12.0 is the last one that works with JDK6. As JDK6 has been EOL'ed for a long time, we decided to drop support for it. Even JDK7 is deprecated and will be EOL'ed in the near future.

If you're bound to JDK6, you can still use 0.12.0

**Comment by tolbertam** [comment]
> If you're bound to JDK6, you can still use 0.12.0

It looks like 0.11.0 is the last that works with JDK6, but that works great for me 👍

**Comment by bric3** [comment]
@hierynomus that's a breaking change that is not even documented in the release notes. The very least would be do increase the major number And to describe the incompatibility.
