### ISSUE TITLE
Unified license report for multi-project build

### ISSUE THREAD

**Issue by shevek** [hierynomus/license-gradle-plugin#40]
It's either missing or nonobvious, but I use the netflix gradle template, which uses this plugin, and it's not clear how to get a unified license report for a multi-project build. I get unified javadoc but not licenses.

Thank you.

**Comment by shevek** [comment]
Update: License plugin currently applied like this, due to Netflix gradle template being obsolete:

https://github.com/shevek/gradle-stdproject-plugin/blob/master/src/main/java/org/anarres/gradle/plugin/stdproject/StdProjectPlugin.java#L177

**Comment by sschuberth** [comment]
As a work-around, you could use Pivotal's [LicenseFinder](https://github.com/pivotal/LicenseFinder) which uses this project underneath when scanning Gradle projects. LicenseFinder collects all results of all supported scanning tools, so you effectively get a unifed report also if you just scan a Gradle multi-project build.

**Comment by jonathannaguin** [comment]
Is there any plan of having this done? Even it is possible to have a report for each sub-project, it would be great to see an aggregate report for all of them.
Thanks!

**Comment by hierynomus** [comment]
Fixed by @jonathannaguin :) Thanks a lot!
