### ISSUE TITLE
Multi-project Builds

### ISSUE THREAD

**Issue by rpmoore** [hierynomus/license-gradle-plugin#50]
Could you please add some examples of configuring the plugin for a multiproject build.  I've been playing around with it and I've not been able to successfully configure the source sets so that my subproject source files are recognized by the plugin.

Thanks!

**Comment by sschuberth** [comment]
I can confirm that using `allprojects` works, so I guess this can be closed. However, this will lead to individual reports per project, not a single report, but that's a [different issue](https://github.com/hierynomus/license-gradle-plugin/issues/40).

**Comment by shevek** [comment]
I agree that `allprojects{}` works, this issue can be closed, and that #40 is my requirement.

**Comment by hierynomus** [comment]
#40 is fixed by @jonathannaguin. Closing this one now
