### ISSUE TITLE
downloadLicenses fails on gradle 2.x

### ISSUE THREAD

**Issue by gomesla** [hierynomus/license-gradle-plugin#54]
When sing the plugin it fails with
Execution failed for task ':downloadLicenses'.
> No signature of method: static com.google.common.collect.HashMultimap.create() is applicable for a
rgument types: () values: []
Possible solutions: clear(), grep(), get(java.lang.Object), get(java.lang.Object), isCase(java.lang.
Object), grep(java.lang.Object)

I tried:
- changing the version of guava everything from 11.0.2 to 18 including the actual dep 17
- changing the gradle version from 2.0, 2.1, 2.2.1

The problem seems to be with the line 241 in LicenseReporter
HashMultimap<LicenseMetadata, String> licensesMap = HashMultimap.create()

**Comment by shevek** [comment]
I got this in 0.11 but not in 0.10 - but 0.11 is latest - so what version should I be running?

**Comment by shevek** [comment]
Oh, I just saw "once I release". Pretty please release it!

**Comment by sschuberth** [comment]
@gomesla @shevek Version 0.12.0 has been released. Could you try with that and close this issue eventually?

**Comment by gomesla** [comment]
closing as fixed in 0.12.0
