### ISSUE TITLE
when is the next release (including android support) planned?

### ISSUE THREAD

**Issue by SierraGolf** [hierynomus/license-gradle-plugin#59]
Hey guys,

I just stumbled across your plugin and saw that it does not yet have support for android, but that you are working on it. Can you give an eta. to when this is going to be released?

Btw. is there a workaround to support android with the current version?

Thanks!
Sebastian

**Comment by hierynomus** [comment]
Hi Sebastian,

I'll perform some work on this next week and then release it. The biggest
part of the code is there now.
It would be a great help if you could test this using a locally built
snapshot of the current master.

Regards,
Jeroen

2015-01-23 10:55 GMT+01:00 Sebastian Gröbler <notifications@github.com>:

**Comment by SierraGolf** [comment]
Sure, I will have a look and give you feedback if anything goes wrong.

**Comment by SierraGolf** [comment]
Hi Jeroen,

I tried master and it works good. I am looking forward to the release!

Cheers,
Sebastian

**Comment by SierraGolf** [comment]
there was one little snag though. I think you need to change the android plugin version to ```1.0.+```. It did not build for me without that.

I am not an expert on gradle versions and ranges and stuff, but it seems that the above is the correct notation. however if the most recent version is specified the plus sign does not seem to harm, which was probably the case when you initially added it.

**Comment by hierynomus** [comment]
Hi Sebastian,

I've changed the dependency info to `1.0.+` now. Could you check whether
that is what you meant?

regards,
Jeroen

2015-01-24 21:06 GMT+01:00 Sebastian Gröbler <notifications@github.com>:

**Comment by SierraGolf** [comment]
Yeah, that's it.

**Comment by ming13** [comment]
@hierynomus Are there any news regarding the future release? Android support is a great and missing feature.
