### ISSUE TITLE
support for supplying license info for "No license found" libraries in report?

### ISSUE THREAD

**Issue by larham** [hierynomus/license-gradle-plugin#69]
How can I add info to supply licensing info for the "No license found" libraries?

In particular, all of the Android support libraries like 

   support-v4-22.1.1.aar

show up under this category, and they are licensed under https://source.android.com/source/licenses.html

**Comment by hierynomus** [comment]
You can supply them in the `licenses` property of the `downloadLicenses` extension. See this (copied from the README):

```
downloadLicenses {
    ext.apacheTwo = license('Apache License, Version 2.0', 'http://opensource.org/licenses/Apache-2.0')
    ext.bsd = license('BSD License', 'http://www.opensource.org/licenses/bsd-license.php')

    includeProjectDependencies = true
    licenses = [
        (group('com.myproject.foo')) : license('My Company License'),
        'org.apache.james:apache-mime4j:0.6' : apacheTwo,
        'org.some-bsd:project:1.0' : bsd
    ]
...
```

**Comment by larham** [comment]
Oh! Thank you for educating me.  

Please consider calling this out with a header in the README, like "Supplying a license for dependencies that lack info in their pom", to assist then next reading-challenged person like me :)

**Comment by hierynomus** [comment]
Will do. thx!
