### ISSUE TITLE
fails when pom has xlint:all in it.

### ISSUE THREAD

**Issue by jclx** [hierynomus/license-gradle-plugin#75]
When generating licenses from this dependency
	runtime 'com.sun.mail:javax.mail:1.5.4'

Execute gradle downloadLicenses
Reports:
> org.xml.sax.SAXParseException; systemId: file://.....gradle/c
aches/modules-2/files-2.1/com.sun.mail/javax.mail/1.5.4/8de39496b150da70dbc2baff
2d80588b332763e6/javax.mail-1.5.4.pom; lineNumber: 116; columnNumber: 17; The pr
efix "Xlint" for element "Xlint:all" is not bound.

Only workaround is excluding it for now.
downloadLicenses {
	excludeDependencies = [
    	'com.sun.mail:javax.mail:1.5.4' // pom has unknown prefix xlint:
	]
}

**Comment by hierynomus** [comment]
This is fixed by https://github.com/hierynomus/license-gradle-plugin/commit/94e964eb0de47903bb5878a73207977c94568dc4

**Comment by hierynomus** [comment]
It will be released in 0.12.0
