### ISSUE TITLE
Copying third party licenses in Gradle?

### ISSUE THREAD

**Issue by alixwar** [hierynomus/license-gradle-plugin#77]
Hi, I've created a post on stackoverflow for a problem that I'm having.

Is this something you can help with? It seems like a good use case for using your plugin

http://stackoverflow.com/questions/31785871/copy-generated-third-party-licenses-to-assets

**Comment by hierynomus** [comment]
Judging from the comments there, your problem is fixed, correct?

**Comment by alixwar** [comment]
Unfortunately not. The answer did not solve my problem.

**Comment by alixwar** [comment]
Maybe this error can help. I was trying to do:

copyToAssets.dependsOn downloadLicenses

Could not determine the dependencies of task ':application:copyToAssets'.
> Cannot convert nl.javadude.gradle.plugins.license.DownloadLicensesExtension_Decorated@59cb18b5 to a task.
  The following types/formats are supported:
    - A String or CharSequence task name or path
    - A Task instance
    - A Buildable instance
    - A TaskDependency instance
    - A Closure instance that returns any of the above types
    - A Callable instance that returns any of the above types
    - An Iterable, Collection, Map or array instance that contains any of the above types

**Comment by hierynomus** [comment]
Could you try:

    copyToAssets.dependsOn project.tasks.getByName('downloadLicenses')

Both the task and the extension are named `downloadLicenses`, so I think that is why you get that message.

**Comment by alixwar** [comment]
Thank you! I will first try a different approach which seems to be working (see post on stackoverflow)

**Comment by alixwar** [comment]
It worked :-)

**Comment by alixwar** [comment]
This solution no longer works as both

`generateDebugResources.dependsOn` tasks['downloadLicenses']
`generateReleaseResources.dependsOn` tasks['downloadLicenses']

are evaluated and now the buildType that is not set will throw an exception. Any advice?
I've created a post on stackoverflow: http://stackoverflow.com/questions/41239220/how-to-add-conditional-afterevaluate-on-buildtype-in-gradle

**Comment by alixwar** [comment]
This is solved. See the stackoverflow post referenced in my last comment for a solution.
