### ISSUE TITLE
Execution failed for task ':downloadLicenses'

### ISSUE THREAD

**Issue by thomasbiesaart** [hierynomus/license-gradle-plugin#89]
Whenever I try to run the downloadLicenses task (no configuration) on my project I get an unknown exception: 
```
* What went wrong:
Execution failed for task ':downloadLicenses'.
> Supplied String module notation '::' is invalid. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.
```

Why is this happening? If there is a known workaround I would like to know it.
To reproduce this error you can simply check out the repository and run the task: https://github.com/thomasbiesaart/wield

**Comment by hierynomus** [comment]
Someone else ran into this and should have fixed this, could you check the latest master to see whether this still occurs?

**Comment by thomasbiesaart** [comment]
Yup latest master seems to work. Thanks.

I'll be waiting for the next release then :) I like the plugin btw
