### ISSUE TITLE
Make the License tasks to be public

### ISSUE THREAD

**Issue by jonathannaguin** [hierynomus/license-gradle-plugin#92]
Gradle has support now for distinguishing between public and internal tasks.
Task is considered to be public if it has a non-null 'group' property. 
See example below:
```
task t1 { 
group "Public" 
description "T1 test task" 
}
```

The current tasks for the license plugin don't have defined a group therefore they are not consider public.
This is important if you use a Gradle plugin in your IDE, (Buildship or STS in Eclipse), as they only show by the default the public tasks.

**Comment by hierynomus** [comment]
Closing this as the PR #93 is merged. Thx!
